#!/bin/sh

if [ -f "/init" ]; then
    /init &
fi

if [ -n "$DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL" ]; then
    DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL=${JENKINS_URL}jnlpJars/agent.jar
fi

if [ -n "$DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL" ]; then
    DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL=${JENKINS_URL}computer/${NODE_NAME}/slave-agent.jnlp
fi

if [ -n "$DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET" ]; then
    DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET=${JNLP_SECRET}
fi

wget -O agent.jar $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL && java -jar agent.jar -jnlpUrl $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL -secret $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET -noReconnect -workDir /home/jenkins
